config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :selectors
  get 'selector' => 'selector#index', as: :selector
  root 'selector#index'
  resources :descriptions

  #patient is as a function of description
  get   'descriptions/:id/patient'      => 'patients#show'   , as: :patient
  get   'descriptions/:id/patients'     => 'patients#show'   , as: :patients
  get   'descriptions/:id/patients/new' => 'patients#new'    , as: :new_patient
  #post  'descriptions/:id/patient'      => 'patients#create'
  post  'descriptions/:id/patient'      => 'patients#create'
  get   'descriptions/:id/patient/edit' => 'patients#edit'   , as: :edit_patient
  patch 'descriptions/:id/patient'      => 'patients#update'

  #mother_datum is as a function of description
  get   'descriptions/:id/mother_datum'      => 'mother_data#show'   , as: :mother_datum
  get   'descriptions/:id/mother_data'       => 'mother_data#show'   , as: :mother_data
  get   'descriptions/:id/mother_data/new'   => 'mother_data#new'    , as: :new_mother_datum
  post  'descriptions/:id/mother_datum'      => 'mother_data#create'
  get   'descriptions/:id/mother_datum/edit' => 'mother_data#edit'   , as: :edit_mother_datum
  patch 'descriptions/:id/mother_datum'      => 'mother_data#update'

  get   'descriptions/:id/external'      => 'external#show'   , as: :external
  get   'descriptions/:id/externals'     => 'external#show'   , as: :externals
  get   'descriptions/:id/externals/new' => 'external#new'    , as: :new_external
  post  'descriptions/:id/external'      => 'external#create'
  get   'descriptions/:id/external/edit' => 'external#edit'   , as: :edit_external
  patch 'descriptions/:id/external'      => 'external#update'

  get   'descriptions/:id/internal'      => 'internal#show'   , as: :internal
  get   'descriptions/:id/internals'     => 'internal#show'   , as: :internals
  get   'descriptions/:id/internals/new' => 'internal#new'    , as: :new_internal
  post  'descriptions/:id/internal'      => 'internal#create'
  get   'descriptions/:id/internal/edit' => 'internal#edit'   , as: :edit_internal
  patch 'descriptions/:id/internal'      => 'internal#update'

  # New paths for four sections of internals
  get   'descriptions/:id/internalhn'      => 'internalhn#show'    , as: :internalhn
  get   'descriptions/:id/internalhn/edit' => 'internalhn#edit'    , as: :edit_internalhn
  post  'descriptions/:id/internalhn'      => 'internalhn#create'
  patch 'descriptions/:id/internalhn'      => 'internalhn#update'
  # New paths for four sections of internals
  get   'descriptions/:id/internalnt'      => 'internalnt#show'    , as: :internalnt
  get   'descriptions/:id/internalnt/edit' => 'internalnt#edit'    , as: :edit_internalnt
  post  'descriptions/:id/internalnt'      => 'internalnt#create'
  patch 'descriptions/:id/internalnt'      => 'internalnt#update'
  # New paths for four sections of internals
  get   'descriptions/:id/internalap'      => 'internalap#show'    , as: :internalap
  get   'descriptions/:id/internalap/edit' => 'internalap#edit'    , as: :edit_internalap
  post  'descriptions/:id/internalap'      => 'internalap#create'
  patch 'descriptions/:id/internalap'      => 'internalap#update'

  get   'descriptions/:id/ancillary_testing'      => 'ancillary_testings#show'   , as: :ancillary_testing
  get   'descriptions/:id/ancillary_testings'     => 'ancillary_testings#show'   , as: :ancillary_testings
  get   'descriptions/:id/ancillary_testings/new' => 'ancillary_testings#new'    , as: :new_ancillary_testing
  post  'descriptions/:id/ancillary_testing'      => 'ancillary_testings#create'
  get   'descriptions/:id/ancillary_testing/edit' => 'ancillary_testings#edit'   , as: :edit_ancillary_testing
  patch 'descriptions/:id/ancillary_testing'      => 'ancillary_testings#update'

  get   'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#show'   , as: :clinico_pathological_summary
  get   'descriptions/:id/clinico_pathological_summaries'     => 'clinico_pathological_summary#show'   , as: :clinico_pathological_summaries
  get   'descriptions/:id/clinico_pathological_summaries/new' => 'clinico_pathological_summary#new'    , as: :new_clinico_pathological_summary
  post  'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#create'
  get   'descriptions/:id/clinico_pathological_summary/edit'  => 'clinico_pathological_summary#edit'   , as: :edit_clinico_pathological_summary
  patch 'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#update'

  get   'descriptions/:id/question_answer'       => 'question_answer#show'   , as: :question_answer
  get   'descriptions/:id/question_answers'      => 'question_answer#show'   , as: :question_answers
  get   'descriptions/:id/question_answers/new'  => 'question_answer#new'    , as: :new_question_answer
  post  'descriptions/:id/question_answer'       => 'question_answer#create'
  get   'descriptions/:id/question_answer/edit'  => 'question_answer#edit'   , as: :edit_question_answer
  patch 'descriptions/:id/question_answer'       => 'question_answer#update'

  get   'descriptions/:id/placenta'       => 'placenta#show'   , as: :placenta
  get   'descriptions/:id/placentas'      => 'placenta#show'   , as: :placentas
  get   'descriptions/:id/placentas/new'  => 'placenta#new'    , as: :new_placenta
  post  'descriptions/:id/placenta'       => 'placenta#create'
  get   'descriptions/:id/placenta/edit'  => 'placenta#edit'   , as: :edit_placenta
  patch 'descriptions/:id/placenta'       => 'placenta#update'

  get   'descriptions/:id/block_codes'         => 'block_codes#show', as: :block_codes
  get   'descriptions/:id/block_codes/new'     => 'block_codes#new', as: :new_block_code
  post  'descriptions/:id/block_codes'         => 'block_codes#create'

  get   'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#show'   , as: :provisional_diagnosis
  get   'descriptions/:id/provisional_diagnoses'       => 'provisional_diagnosis#show'   , as: :provisional_diagnoses
  get   'descriptions/:id/provisional_diagnoses/new'   => 'provisional_diagnosis#new'    , as: :new_provisional_diagnosis
  post  'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#create'
  get   'descriptions/:id/provisional_diagnosis/edit'  => 'provisional_diagnosis#edit'   , as: :edit_provisional_diagnosis
  patch 'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#update'

  get   'descriptions/:id/final_diagnosis'       => 'final_diagnosis#show'   , as: :final_diagnosis
  get   'descriptions/:id/final_diagnoses'       => 'final_diagnosis#show'   , as: :final_diagnoses
  get   'descriptions/:id/final_diagnoses/new'   => 'final_diagnosis#new'    , as: :new_final_diagnosis
  post  'descriptions/:id/final_diagnosis'       => 'final_diagnosis#create'
  get   'descriptions/:id/final_diagnosis/edit'  => 'final_diagnosis#edit'   , as: :edit_final_diagnosis
  patch 'descriptions/:id/final_diagnosis'       => 'final_diagnosis#update'


  get  'descriptions/:id/specialreport/'                     => 'special_report#index' , as: :special_report
  get  'descriptions/:id/specialreport/new'                  => 'special_report#new', as: :new_special_report
  post 'descriptions/:id/specialreport/create'              => 'special_report#create', as: :create_special_report
  get  'descriptions/:id/specialreport/:report_id/edit'      => 'special_report#edit', as: :edit_special_report
  post 'descriptions/:id/specialreport/:report_id/update'   => 'special_report#update', as: :update_special_report
  get  'descriptions/:id/specialreport/:report_id/delete'    => 'special_report#delete', as: :delete_special_report
  post 'descriptions/:id/specialreport/:report_id/signout'  => 'special_report#sign_out', as: :signout_special_report
  get  'descriptions/:id/specialreport/:report_id/show'      => 'special_report#show', as: :show_special_report

  get   'descriptions/:id/final_report'       => 'final_report#show'   , as: :show_final_report
  get   'descriptions/:id/final_report/new'   => 'final_report#new'    , as: :new_final_report
  post  'descriptions/:id/final_report'       => 'final_report#create' , as: :create_final_report
  get   'descriptions/:id/final_report/edit'  => 'final_report#edit'   , as: :edit_final_report
  patch 'descriptions/:id/final_report'       => 'final_report#update' , as: :update_final_report
  post  'descriptions/:id/final_report/signout'  => 'final_report#sign_out', as: :signout_final_report

  # For full report
  get  'descriptions/:id/fullreport/show'      => 'full_report#show', as: :show_full_report
end

app/models/special_report.rb
class SpecialReport < ActiveRecord::Base
	belongs_to :description
end

app/controllers/special_report_controller.rb
class SpecialReportController < ApplicationController

  before_action :set_description
  
  #GET 
  def index
    @special_reports = @description.special_reports.all
  end

  # 
  def new
    @special_report = @description.special_reports.build
    authorize! :create, @special_report 
  end

  def create
    @special_report = @description.special_reports.build(special_report_params)
    authorize! :create, @special_report
    respond_to do |format|
      if @special_report.save
        format.html{ redirect_to "#{description_path}#special", notice: "A special report was successfully created!" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @special_report = @description.special_reports.find(params[:report_id])
    #authorize! :update, @special_report rescue authorize! :update_if_assigned, @special_report
    authorize! :update, SpecialReport 
    unless @special_report.lock.nil?
      email     = params[:sign_out][:email]
      password  = params[:sign_out][:password]
      user = User.find_by_email(email)
      respond_to do |format|
        if !user.nil? and user.valid_password?(password) and user == User.find(@special_report.assign)
          format.html { render :edit, notice: "Assigned user was successfully logged in!" }
        else
          format.html{ redirect_to "#{description_path}#special", notice: "The email and/or password entered is/are incorrect." }
        end
      end
    end

  end

  def show
    @special_report = @description.special_reports.find(params[:report_id])
    authorize! :see , @special_report rescue authorize! :see_if_assigned, @special_report
  end

  def update
    #authorize! :update, @special_report  rescue authorize! :update_if_assigned, @special_report
    authorize! :update, SpecialReport 
    @special_report = @description.special_reports.find(params[:report_id])
    respond_to do |format|
      if @special_report.update(special_report_params)
        format.html{ redirect_to "#{description_path}#special", notice: "A special report was successfully updated!" }
      else
        format.html { render :edit }
      end
    end
  end

  def delete
    @special_report = @description.special_reports.find(params[:report_id])
    respond_to do |format|
      if @special_report.destroy
        format.html{ redirect_to "#{description_path}#special", notice: "A special report was successfully deleted!" }
      else
        format.html { render :edit }
      end
    end
  end

  def sign_out
    @special_report = @description.special_reports.find(params[:report_id])
    email     = params[:sign_out][:email]
    password  = params[:sign_out][:password]
    user = User.find_by_email(email)
    if !user.nil? and user.valid_password?(password) and user == User.find(@special_report.assign)
      if @special_report.update(:lock => email)
        @result = 'success' 
      else
        @result = 'failure'
      end
    else
      @result = 'failure'
    end      
    # respond_to do |f|      
    #   f.js { render layout: false, content_type: 'text/javascript' }
    #   f.html
    # end           
  end

  def set_description
    @description = Description.find(params[:id])

  end

  def special_report_params
    params.require("special_report").permit(:title, :final_diagnosis, :gross_description, :blockcode, :microscopic_description, :assign, :lock)
  end

  def signout_params
    params.require("sign_out").permit(:email, :password)
  end

end

app/views/special_report/_index.html.erb
<p id="notice"><%= notice %></p>

<%= render "layouts/basic" %>
<%= render "layouts/complete" %>

app/views/special_report/_index_of_report.html.erb
<br>
  <div class="row">
    <% if ! @description.special_reports.nil? %>
      <div class="col-sm-12">
	<% all_description = @description.special_reports.all.sort_by {|cyclist| cyclist.id} %>
	<table class="table table-condensed">
	  <thead>
	    <tr>
	      <th>Title</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% all_description.each do |report| %>
	      <% if report.lock.nil? %>
		<tr>
		  <td> <%= report.title %>
		</td>
		<td>
                <% if can? :update , SpecialReport %>
		  <%= link_to "Edit" , 
		  edit_special_report_path(@description.id, report.id), 
		  class: 'btn btn-xs btn-success' %>  
	        <% end %>
	      </td>
		</tr>
	      <% else %>
		<tr>
		  <td> 
		    <%= report.title %>
		  </td>
		  <td> 
		    <a href="<%= show_special_report_path(@description.id, report.id ) %>" 
	 class="btn btn-xs btn-warning" >
	 Signed Out
		    </a >
		  </td>
		</tr>
	      <% end %>
	    <% end %>
	  </tbody>
	</table>
      </div>
      <% end %>

      <div class="col-sm-12">
       <% if can? :create, SpecialReport %>
	<%= link_to 'Add special report', new_special_report_path, class: 'btn btn-primary' %>
       <% end %>
      </div>
  </div>

app/views/special_report/edit.html.erb
<!-- edit special report -->
<!-- <h1>Edit special report</h1> -->
<div class="special-report-form">
<%= form_for :special_report, url: update_special_report_path(@description.id, @special_report.id), html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <label class="control-label col-sm-3" for="email">Title:</label>
    <div class="col-sm-9">
    	<%= f.text_field :title, :class => 'form-control', value: @special_report.title %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Final diagnosis:</label>
    <div class="col-sm-9"> 
      <%= f.text_area :final_diagnosis, :class => 'tinymce form-control', rows: 10, value: @special_report.final_diagnosis %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Gross description:</label>
    <div class="col-sm-9">
      <%= f.text_area :gross_description, :class => 'tinymce form-control', value: @special_report.gross_description, rows: 10 %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" ><a data-dismiss="modal" data-toggle="modal" data-target="#blockModal">Block code:</a></label>
    <div class="col-sm-9"> 
      <input type="text" class="form-control">
      <!-- <select name="special_report[blockcode]" class="form-control", value="<%= @special_report.blockcode %>" >
      	<% BlockCode.all.each do |blockcode| %>
      		<option value="<%= blockcode.id %>"><%= blockcode.block_description %></option>      	
      	<% end %>
      </select> -->
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Micropscopic description:</label>
    <div class="col-sm-9"> 
      <%= f.text_area :microscopic_description, :class => 'tinymce form-control', value: @special_report.microscopic_description, rows: 10 %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :assign, "Assign", :class => "control-label col-sm-3" %>
    <div class="col-sm-9"> 
      <%= select_tag "special_report[assign]" , 
	options_for_select( User.all.collect{ |u| [u.email, u.id] }, 
		     @special_report.assign ) , 
	{ :prompt => "Select one", class: "form-control" } %>
    </div>
  </div>
  <br>
  <div class="form-group"> 
    <div class="col-sm-offset-6 col-sm-2">
      <button type="submit" class="btn btn-primary">Save and Exit</button>
    </div>
    <div class="col-sm-2">
      <a href="#" data-toggle="modal" data-target="#alertModal" class="btn btn-success signout-report">Sign out</a>
    </div>
    <div class="col-sm-2">
      <a href="<%= delete_special_report_path(@description.id, @special_report.id) %>" class="btn btn-danger">Delete</a>
    </div>
  </div>  
<% end %>
<!-- end form -->
</div>

<div id="alertModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign out</h4>
      </div>
      <div class="modal-body">
        <p>"This action will finalize the <b><%= @special_report.title%></b> report in its present from and you will not be allowed to make any changes to it. You can continue to make changes to the remainder of the autopsy report. Do you want to continue?"</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target="#loginModal">Yes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>

<div id="loginModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>        
        <h4 class="modal-title">Log in for Sign out</h4>
      </div>
 <!-- form start -->
      <%= form_for :sign_out, url: signout_special_report_path(@description.id, @special_report.id), remote: true, method: :post do |d|%>
       <div class="modal-body form-horizontal">
        <div class="form-group">
          <label class="control-label col-sm-3" >Email:</label>
          <div class="col-sm-9">
            <%= d.email_field :email, :class => 'form-control', :required => 'true' %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3" >Password:</label>
          <div class="col-sm-9">
            <%= d.password_field :password, :class => 'form-control', :required => 'true' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" >Login</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
      <% end %>
<!-- form end -->
    </div>
  </div>
</div>
<
<div id="resultModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <!-- Modal content-->
    <div class="modal-content">      
      <div class="modal-body">
        <p class="signout-result"></p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="blockModal" tabindex="1" role="dialog" aria-labelledby="todo-label" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
    <h4 class="modal-title" id="todo-label">Manage codes</h4>
         </div>
         <div class="modal-body">
         <%= render 'block_codes/manage' %>
         </div>
         <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
         </div>
       </div>
     </div>
   </div>
<script type="text/javascript">
  tinyMCE.init({
      selector: "textarea.tinymce",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "left",
      theme_advanced_statusbar_location: "bottom",
      theme_advanced_buttons3_add: null,
      toolbar: "bold italic",
      plugins: "table"
    });
</script>

app/views/special_report/new.html.erb
<!-- create special report -->

<h1>Add new special report</h1>
<div class="special-report-form">
<%= form_for :special_report, url: create_special_report_path(@description.id), html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <label class="control-label col-sm-3" for="email">Title:</label>
    <div class="col-sm-9">
    	<%= f.text_field :title, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Final diagnosis:</label>
    <div class="col-sm-9">
      <%= f.text_area :final_diagnosis, :class => 'form-control tinymce', rows: 10 %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Gross description:</label>
    <div class="col-sm-9">
      <%= f.text_area :gross_description, :class => 'form-control tinymce', rows: 10 %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" ><a data-dismiss="modal" data-toggle="modal" data-target="#blockModal">Block code:</a></label>
    <div class="col-sm-9"> 
      <input type="text" class="form-control">
      <!-- <select name="special_report[blockcode]" class="form-control", value="<%= @special_report.blockcode %>" >
        <% BlockCode.all.each do |blockcode| %>
          <option value="<%= blockcode.id %>"><%= blockcode.block_description %></option>       
        <% end %>
      </select> -->
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Micropscopic description:</label>
    <div class="col-sm-9"> 
      <%= f.text_area :microscopic_description, :class => 'form-control tinymce', rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :assign, "Assign", :class => "control-label col-sm-3" %>
    <div class="col-sm-9"> 
      <%= select_tag "special_report[assign]" , 
	options_for_select( User.all.collect{ |u| [u.email, u.id] }, 
			   @special_report.assign ) , 
			   { :prompt => "Select one", class: "form-control" } %>
  </div>
  </div>

  <br>
 
  <div class="form-group"> 
    <div class="col-sm-offset-3 col-sm-10">
      <button type="submit" class="btn btn-primary">Save and Exit</button>
    </div>   
  </div>  
<% end %>
</div>

<div class="modal fade" id="blockModal" tabindex="1" role="dialog" aria-labelledby="todo-label" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
          <h4 class="modal-title" id="todo-label">Manage codes</h4>
       </div>
       <div class="modal-body">
       <%= render 'block_codes/manage' %>
       </div>
       <div class="modal-footer">
      <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
       </div>
     </div>
   </div>
 </div>

<script type="text/javascript">
  tinyMCE.init({
      selector: "textarea.tinymce",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "left",
      theme_advanced_statusbar_location: "bottom",
      theme_advanced_buttons3_add: null,
      toolbar: "bold italic",
      plugins: "table"
    });
</script>

app/views/special_report/show.html.erb
<!-- edit special report -->
<!-- <h1>Show special report</h1>
 --><div class="special-report-form form-horizontal">
  <div class="form-group">
    <label class="control-label col-sm-3" for="email">Title:</label>
    <div class="col-sm-9">
      <div class="form-control"><%= @special_report.title %></div>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Final diagnosis:</label>
    <div class="col-sm-9">
      <div class="panel"><%= @special_report.final_diagnosis.html_safe %></div>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Gross description:</label>
    <div class="col-sm-9">
      <div class="panel"><%= @special_report.gross_description.html_safe %></div>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Block code:</label>
    <div class="col-sm-9"> 
       
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Micropscopic description:</label>
    <div class="col-sm-9">
     <div class="panel"><%= @special_report.microscopic_description.html_safe %></div>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-3" >Assign to:</label>
    <div class="col-sm-9"> 
      <div class="form-control"><%= User.find(@special_report.assign).email %></div>     	
    </div>
  </div>
  <br>
  <!-- <div class="form-group"> 
    <div class="col-sm-2 col-sm-offset-8">
      <% if @special_report.lock.nil? %>
        <%= link_to ' Edit ', edit_special_report_path(@description.id, @special_report.id), class: 'btn btn-success' %>  
      <% else %>
        <a class="btn btn-warning" data-toggle="modal" data-target="#loginModal" > Edit </a> 
      <% end %>
    </div>
    <div class="col-sm-2">
      <a href="<%= delete_special_report_path(@description.id, @special_report.id) %>" class="btn btn-danger">Delete</a>
    </div>
  </div>  --> 

<!-- end form -->
</div>

<div id="loginModal" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>        
                <h4 class="modal-title">Log in for Sign out</h4>
              </div>
         <!-- form start -->
              <%= form_for :sign_out, url: edit_special_report_path(@description.id, @special_report.id), method: :get do |d|%>
               <div class="modal-body form-horizontal">
                <div class="form-group">
                  <label class="control-label col-sm-3" >Email:</label>
                  <div class="col-sm-9">
                    <%= d.email_field :email, :class => 'form-control', :required => 'true' %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-3" >Password:</label>
                  <div class="col-sm-9">
                    <%= d.password_field :password, :class => 'form-control', :required => 'true' %>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary" >Login</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>
              <% end %>
        <!-- form end -->
            </div>
          </div>
        </div> 

<script type="text/javascript">
  tinyMCE.init({
      selector: "textarea.tinymce",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "left",
      theme_advanced_statusbar_location: "bottom",
      theme_advanced_buttons3_add: null,
      toolbar: "bold italic",
      plugins: "table"
    });
</script>

app/views/special_report/sign_out.js.erb
	$('#loginModal').modal('hide');
<% if @result == 'success' %>
	$('#resultModal p.signout-result').html('The <b><%=@special_report.title %></b> report is signed out');
<% else %>
	$('#resultModal p.signout-result').html('The email and/or password entered is/are incorrect.');
<% end %>
	$('#resultModal').modal('show');