config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :selectors
  get 'selector' => 'selector#index', as: :selector
  root 'selector#index'
  resources :descriptions

  #patient is as a function of description
  get   'descriptions/:id/patient'      => 'patients#show'   , as: :patient
  get   'descriptions/:id/patients'     => 'patients#show'   , as: :patients
  get   'descriptions/:id/patients/new' => 'patients#new'    , as: :new_patient
  #post  'descriptions/:id/patient'      => 'patients#create'
  post  'descriptions/:id/patient'      => 'patients#create'
  get   'descriptions/:id/patient/edit' => 'patients#edit'   , as: :edit_patient
  patch 'descriptions/:id/patient'      => 'patients#update'

  #mother_datum is as a function of description
  get   'descriptions/:id/mother_datum'      => 'mother_data#show'   , as: :mother_datum
  get   'descriptions/:id/mother_data'       => 'mother_data#show'   , as: :mother_data
  get   'descriptions/:id/mother_data/new'   => 'mother_data#new'    , as: :new_mother_datum
  post  'descriptions/:id/mother_datum'      => 'mother_data#create'
  get   'descriptions/:id/mother_datum/edit' => 'mother_data#edit'   , as: :edit_mother_datum
  patch 'descriptions/:id/mother_datum'      => 'mother_data#update'

  get   'descriptions/:id/external'      => 'external#show'   , as: :external
  get   'descriptions/:id/externals'     => 'external#show'   , as: :externals
  get   'descriptions/:id/externals/new' => 'external#new'    , as: :new_external
  post  'descriptions/:id/external'      => 'external#create'
  get   'descriptions/:id/external/edit' => 'external#edit'   , as: :edit_external
  patch 'descriptions/:id/external'      => 'external#update'

  get   'descriptions/:id/internal'      => 'internal#show'   , as: :internal
  get   'descriptions/:id/internals'     => 'internal#show'   , as: :internals
  get   'descriptions/:id/internals/new' => 'internal#new'    , as: :new_internal
  post  'descriptions/:id/internal'      => 'internal#create'
  get   'descriptions/:id/internal/edit' => 'internal#edit'   , as: :edit_internal
  patch 'descriptions/:id/internal'      => 'internal#update'

  # New paths for four sections of internals
  get   'descriptions/:id/internalhn'      => 'internalhn#show'    , as: :internalhn
  get   'descriptions/:id/internalhn/edit' => 'internalhn#edit'    , as: :edit_internalhn
  post  'descriptions/:id/internalhn'      => 'internalhn#create'
  patch 'descriptions/:id/internalhn'      => 'internalhn#update'
  # New paths for four sections of internals
  get   'descriptions/:id/internalnt'      => 'internalnt#show'    , as: :internalnt
  get   'descriptions/:id/internalnt/edit' => 'internalnt#edit'    , as: :edit_internalnt
  post  'descriptions/:id/internalnt'      => 'internalnt#create'
  patch 'descriptions/:id/internalnt'      => 'internalnt#update'
  # New paths for four sections of internals
  get   'descriptions/:id/internalap'      => 'internalap#show'    , as: :internalap
  get   'descriptions/:id/internalap/edit' => 'internalap#edit'    , as: :edit_internalap
  post  'descriptions/:id/internalap'      => 'internalap#create'
  patch 'descriptions/:id/internalap'      => 'internalap#update'

  get   'descriptions/:id/ancillary_testing'      => 'ancillary_testings#show'   , as: :ancillary_testing
  get   'descriptions/:id/ancillary_testings'     => 'ancillary_testings#show'   , as: :ancillary_testings
  get   'descriptions/:id/ancillary_testings/new' => 'ancillary_testings#new'    , as: :new_ancillary_testing
  post  'descriptions/:id/ancillary_testing'      => 'ancillary_testings#create'
  get   'descriptions/:id/ancillary_testing/edit' => 'ancillary_testings#edit'   , as: :edit_ancillary_testing
  patch 'descriptions/:id/ancillary_testing'      => 'ancillary_testings#update'

  get   'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#show'   , as: :clinico_pathological_summary
  get   'descriptions/:id/clinico_pathological_summaries'     => 'clinico_pathological_summary#show'   , as: :clinico_pathological_summaries
  get   'descriptions/:id/clinico_pathological_summaries/new' => 'clinico_pathological_summary#new'    , as: :new_clinico_pathological_summary
  post  'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#create'
  get   'descriptions/:id/clinico_pathological_summary/edit'  => 'clinico_pathological_summary#edit'   , as: :edit_clinico_pathological_summary
  patch 'descriptions/:id/clinico_pathological_summary'       => 'clinico_pathological_summary#update'

  get   'descriptions/:id/question_answer'       => 'question_answer#show'   , as: :question_answer
  get   'descriptions/:id/question_answers'      => 'question_answer#show'   , as: :question_answers
  get   'descriptions/:id/question_answers/new'  => 'question_answer#new'    , as: :new_question_answer
  post  'descriptions/:id/question_answer'       => 'question_answer#create'
  get   'descriptions/:id/question_answer/edit'  => 'question_answer#edit'   , as: :edit_question_answer
  patch 'descriptions/:id/question_answer'       => 'question_answer#update'

  get   'descriptions/:id/placenta'       => 'placenta#show'   , as: :placenta
  get   'descriptions/:id/placentas'      => 'placenta#show'   , as: :placentas
  get   'descriptions/:id/placentas/new'  => 'placenta#new'    , as: :new_placenta
  post  'descriptions/:id/placenta'       => 'placenta#create'
  get   'descriptions/:id/placenta/edit'  => 'placenta#edit'   , as: :edit_placenta
  patch 'descriptions/:id/placenta'       => 'placenta#update'

  get   'descriptions/:id/block_codes'         => 'block_codes#show', as: :block_codes
  get   'descriptions/:id/block_codes/new'     => 'block_codes#new', as: :new_block_code
  post  'descriptions/:id/block_codes'         => 'block_codes#create'

  get   'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#show'   , as: :provisional_diagnosis
  get   'descriptions/:id/provisional_diagnoses'       => 'provisional_diagnosis#show'   , as: :provisional_diagnoses
  get   'descriptions/:id/provisional_diagnoses/new'   => 'provisional_diagnosis#new'    , as: :new_provisional_diagnosis
  post  'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#create'
  get   'descriptions/:id/provisional_diagnosis/edit'  => 'provisional_diagnosis#edit'   , as: :edit_provisional_diagnosis
  patch 'descriptions/:id/provisional_diagnosis'       => 'provisional_diagnosis#update'

  get   'descriptions/:id/final_diagnosis'       => 'final_diagnosis#show'   , as: :final_diagnosis
  get   'descriptions/:id/final_diagnoses'       => 'final_diagnosis#show'   , as: :final_diagnoses
  get   'descriptions/:id/final_diagnoses/new'   => 'final_diagnosis#new'    , as: :new_final_diagnosis
  post  'descriptions/:id/final_diagnosis'       => 'final_diagnosis#create'
  get   'descriptions/:id/final_diagnosis/edit'  => 'final_diagnosis#edit'   , as: :edit_final_diagnosis
  patch 'descriptions/:id/final_diagnosis'       => 'final_diagnosis#update'


  get  'descriptions/:id/specialreport/'                     => 'special_report#index' , as: :special_report
  get  'descriptions/:id/specialreport/new'                  => 'special_report#new', as: :new_special_report
  post 'descriptions/:id/specialreport/create'              => 'special_report#create', as: :create_special_report
  get  'descriptions/:id/specialreport/:report_id/edit'      => 'special_report#edit', as: :edit_special_report
  post 'descriptions/:id/specialreport/:report_id/update'   => 'special_report#update', as: :update_special_report
  get  'descriptions/:id/specialreport/:report_id/delete'    => 'special_report#delete', as: :delete_special_report
  post 'descriptions/:id/specialreport/:report_id/signout'  => 'special_report#sign_out', as: :signout_special_report
  get  'descriptions/:id/specialreport/:report_id/show'      => 'special_report#show', as: :show_special_report

  get   'descriptions/:id/final_report'       => 'final_report#show'   , as: :show_final_report
  get   'descriptions/:id/final_report/new'   => 'final_report#new'    , as: :new_final_report
  post  'descriptions/:id/final_report'       => 'final_report#create' , as: :create_final_report
  get   'descriptions/:id/final_report/edit'  => 'final_report#edit'   , as: :edit_final_report
  patch 'descriptions/:id/final_report'       => 'final_report#update' , as: :update_final_report
  post  'descriptions/:id/final_report/signout'  => 'final_report#sign_out', as: :signout_final_report

  # For full report
  get  'descriptions/:id/fullreport/show'      => 'full_report#show', as: :show_full_report
end

app/controllers/mother_data_controller.rb
class MotherDataController < ApplicationController
  #before_action :set_patient, only: [:show, :edit, :update, :destroy]
	#
  def index
    @descriptions = Description.all
  end

  def show
	  @description = Description.find(params[:id])
          @patient     = @description.mother_datum
	  authorize! :see, @description.mother_datum
  end

  def new
	  @description = Description.find(params[:id])

	  if @description.mother_datum.nil?
	    @mother_datum = MotherDatum.new
	  else
	    respond_to do |format|
	     format.html { redirect_to mother_datum_path, notice: 'Patients mother datum is Already Generated.' }
	    end
	  end
	  authorize! :create, @description.mother_datum
  end

  def edit
     @description = Description.find(params[:id])
     authorize! :update, @description.mother_datum
     @mother_datum     = @description.mother_datum
  end

  def create
    @description = Description.find(params[:id])
    @description.mother_datum = MotherDatum.new(params[:mother_datum].permit([:mother_age, :gestational_age, :prenatal_care, :gravida, :para, :abortus, :term, :pre_pregnancy_weight, :delivery_weight, :blood_type, :antibody_screen, :rpr, :hepatitis_b, :rubella, :HIV, :diabetes, :GBS, :amniocentesis, :previous_pregnancy_summary, :present_pregnancy_summary, :ultrasound_finding, :birth_weight, :maceration_degree, :gross_appearance, :placenta_available_for_examination, :amniotic_fluid, :mother_medical_history, :description, :living, :height, :feto_placental_findings_at_the_time_of_delivery, :pre_pregnancy_bmi, :delivery_bmi, :height_unit, :pre_pregnancy_weight_unit, :delivery_weight_unit, :amniocentesis_explain, :birth_weight_unit, :placenta_specify, :amniotic_fluid_specify , :placenta, :type_of_delivery , :type_of_delivery_specify]))
    #Description.find(params[:id])
    authorize! :create, @description.mother_datum

    respond_to do |format|
      if @description.mother_datum.save

	format.html { redirect_to "#{description_path}#mother", notice: 'Patients Organ weight is  successfully created.' }
	format.json { render :show, status: :ok, location: @description.mother_datum }
      else
        format.html { render :new }
        format.json { render json: @description.mother_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @description = Description.find(params[:id])
    authorize! :update, @description.mother_datum
    respond_to do |format|
      if @description.mother_datum.update(params[:mother_datum].permit([:mother_age, :gestational_age, :prenatal_care, :gravida, :para, :abortus, :term, :pre_pregnancy_weight, :delivery_weight, :blood_type, :antibody_screen, :rpr, :hepatitis_b, :rubella, :HIV, :diabetes, :GBS, :amniocentesis, :previous_pregnancy_summary, :present_pregnancy_summary, :ultrasound_finding, :birth_weight, :maceration_degree, :gross_appearance, :placenta_available_for_examination, :amniotic_fluid, :mother_medical_history, :description, :living, :height, :feto_placental_findings_at_the_time_of_delivery, :pre_pregnancy_bmi, :delivery_bmi, :height_unit, :pre_pregnancy_weight_unit, :delivery_weight_unit, :amniocentesis_explain, :birth_weight_unit, :placenta_specify, :amniotic_fluid_specify, :placenta, :type_of_delivery , :type_of_delivery_specify]))

        format.html { redirect_to "#{description_path}#mother", notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @description.mother_datum }
      else
        format.html { render :edit }
        format.json { render json: @description.mother_datum.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/mother_data_helper.rb
module MotherDataHelper
end

app/views/mother_data/_form.js.erb
addEventListener("change", function() {
 setConditions()
 whatDoesCheckBoxSay()
});

addEventListener("load", function() {
 setConditions()
 whatDoesCheckBoxSay()
});

function whatDoesCheckBoxSay() {
  var checkBoxValue = document.getElementById('fp-finding')
  console.log(checkBoxValue)
  var attributeSelector = checkBoxValue.getAttribute('please_show_type')
  var targetText = checkBoxValue.getAttribute('please_show_names')
  var indComp1 = $( "input[name='mother_datum[feto_placental_findings_at_the_time_of_delivery]']")[0]
  var indComp2 = $( "input[name='mother_datum[feto_placental_findings_at_the_time_of_delivery]']")[1]
  console.log(indComp1)
  console.log(indComp2)
  if(attributeSelector == 'class'){ 
   if(indComp1.checked == true) {
     var all_class = document.getElementsByClassName(targetText)
     for( j = 0; j < all_class.length; j++ ){
      var abc = all_class[j]
      abc.style.display = 'inherit'
      console.log('done')
     }
    }
   else {
    var all_class = document.getElementsByClassName(targetText)
    for( j = 0; j < all_class.length; j++ ){
       var abc = all_class[j]
       abc.style.display = 'none'
    }
   }
  }
  }

  function setConditions(){
  var all_class = document.getElementsByClassName('conditional')
  for( j = 0; j < all_class.length; j++ ){
  var abc = all_class[j]
  var when_answer = abc.getAttribute('when_answer')
  var todisable = abc.getAttribute('todisable')
  takeAction(abc.value, when_answer, todisable)
  }
  }

  function takeAction(given,enable_when,todisable){
  if (given != enable_when){
  disableDisplay(todisable)
  }
  else {
  enableDisplay(todisable)
  }
  }

  function enableDisplay (inarray){
  inarray = inarray.split(' ')
  for(i = 0 ; i < inarray.length ; i++){
  temp1 = document.getElementById(inarray[i])
  temp1.removeAttribute('disabled')
  }
  }
  function disableDisplay (inarray){
  inarray = inarray.split(' ')
  for(i = 0 ; i < inarray.length ; i++){
  temp1 = document.getElementById(inarray[i])
  temp1.setAttribute('disabled','')
  }
  }

app/views/mother_data/_show.html.erb
<div>
  <br>
  <div class="panel panel-mother">
    <div class="panel-heading panel-heading-mother">
      <span class="fa fa-heart-o pull-left"></span>Mother's Vitals
    </div>
    <div class="panel-body panel-body-mother">
      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Age:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= "#{@description.mother_datum.mother_age} Years" %> <br> 
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Prenatal Care:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.prenatal_care %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Gravida:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.gravida %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Para:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.para %><br>
	</div>
      </div>

      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Abortus:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.abortus %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Term:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.term %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Living:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.living %><br>
	</div>
      </div>

      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Height:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.height %>
	  <%= @description.mother_datum.height_unit %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Pre Preg Weight:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.pre_pregnancy_weight %> 
	  <%= @description.mother_datum.pre_pregnancy_weight_unit %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Delivery Weight:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.delivery_weight %>
	  <%= @description.mother_datum.delivery_weight_unit %>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Pre pregnancy BMI:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.pre_pregnancy_bmi %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Delivery BMI:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.delivery_bmi %><br>
	</div>
      </div>
    </div>
  </div>

  <div class="panel panel-mother">
    <div class="panel-heading panel-heading-mother">
      <span class="fa fa-check pull-left"></span>Mother's Antenatal Screening
    </div>
    <div class="panel-body panel-body-mother">
      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Blood Type:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.blood_type %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Antibody Screen:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.antibody_screen %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>RPR:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.rpr %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Hep B:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.hepatitis_b %><br>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Rubella:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.rubella %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>HIV:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.HIV %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>Diabetes:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.diabetes %><br>
	</div>
	<div class="col-sm-2 custom-prop">
	  <strong>GBS:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.GBS %><br>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 custom-prop">
	  <strong>Amniocentesis:</strong>
	</div>
	<div class="col-sm-1 custom-val">
	  <%= @description.mother_datum.amniocentesis %><br>
	</div>
      </div>
    </div>
  </div>

  <div class="panel panel-mother">
    <div class="panel-heading panel-heading-mother">
      <span class="fa fa-history pull-left"></span>Mother's Medical History
    </div>
    <div class="panel-body panel-body-mother">
      <div class="row">
	<div class="col-sm-12 custom-val">
	  <%= @description.mother_datum.mother_medical_history.html_safe %><br>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-3 custom-prop">
	  <strong>Previous Pregnancy Summary:</strong>
	</div>
	<div class="col-sm-9 custom-val">
	  <%= @description.mother_datum.previous_pregnancy_summary.html_safe %>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-3 custom-prop">
	  <strong>Present Pregnancy Summary:</strong>
	</div>
	<div class="col-sm-9 custom-val">
	  <%= @description.mother_datum.present_pregnancy_summary.html_safe %>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-3 custom-prop">
	  <strong>Ultrasound findings:</strong>
	</div>
	<div class="col-sm-9 custom-val">
	  <%= @description.mother_datum.ultrasound_finding.html_safe %>
	</div>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-mother">
  <div class="panel-heading panel-heading-mother">
    <span class="fa fa-child pull-left"></span>Feto placental findings
  </div>
  <div class="panel-body panel-body-mother">
    <div class="row">
      <div class="col-sm-2 custom-prop">
	<strong>Type of Delivery:</strong>
      </div>
      <div class="col-sm-10 custom-val">
	<% if @description.mother_datum.type_of_delivery == "other" %>
	  <%= @description.mother_datum.type_of_delivery_specify %><br>
	<% else %>
	  <%= @description.mother_datum.type_of_delivery %>
	<% end %>
      </div>
      <div class="col-sm-2 custom-prop">
	<strong>Birth Weight:</strong>
      </div>
      <div class="col-sm-4 custom-val">
	<%= @description.mother_datum.birth_weight %><br>
      </div>
      <!--
      <div class="col-sm-2 custom-prop">
	<strong>Degree Of Maceration:</strong>
      </div>
      <div class="col-sm-1 custom-val">
	<%= @description.mother_datum.maceration_degree %><br>
      </div>
      -->
      <div class="col-sm-2 custom-prop">
	<strong>Fetal Appearance:</strong>
      </div>
      <div class="col-sm-4 custom-val">
	<%= @description.mother_datum.gross_appearance %><br>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2 custom-prop">
	<strong>Placenta:</strong>
      </div>
      <div class="col-sm-4 custom-val">
	<% if @description.mother_datum.placenta == "abnormal" %>
	  <%= @description.mother_datum.placenta_specify %><br>
	<% else %>
	  <%= @description.mother_datum.placenta %>
	<% end %>
      </div>
      <div class="col-sm-2 custom-prop">
	<strong>Amniotic Fluid:</strong>
      </div>
      <div class="col-sm-4 custom-val">
	<% if @description.mother_datum.amniotic_fluid == "other" %>
	  <%= @description.mother_datum.amniotic_fluid_specify %><br>
	<% else %>
	  <%= @description.mother_datum.amniotic_fluid %>
	<% end %>
      </div>
    </div>
  </div>
</div>

<% if can? :update, MotherDatum %>
<%= link_to 'Edit Mothers Information', edit_mother_datum_path(@description), class: 'btn btn-primary' %> 
<% end %>

app/views/mother_data/edit.html.erb
<%= render 'form' %>
<%= link_to 'Discard', "#{description_path}#mother", class: 'btn btn-success' %>

app/views/mother_data/new.html.erb
<h1> Provide information about mother </h1>

<%#= render 'layouts/basic' %>
<%#= render 'layouts/complete' %>
<%= render 'form' %>
<%#= render 'layouts/back' %>

<div class="text-left">
  <%= link_to 'Discard', "#{description_path}#mother" , class: 'btn btn-success' %>
</div>

app/views/mother_data/old_show.html.erb
<p id="notice"><%= notice %></p>

<%= render "layouts/basic" %>
<%= render "layouts/complete" %>

<div class="row">
 <div id="patient_name col-sm-12">
  <h3>Patient Name: <%= @patient.name %></h3>
 </div>
</div>

<hr>

<div class="row">
 <div id="patient_age" class="col-sm-3">
	 <strong>Age:</strong>
         <%=@patient.age %>
         <br>
	 <strong>Race:</strong>
         <%= @patient.race %>
         <br>
         <strong>Date of Birth:</strong>
         <%= @patient.dob %>
         <br>
         <strong>Sex:</strong>
         <%= @patient.sex %>
 </div>
 <div id="dates" class="col-sm-4">
   <strong>Date of admission:</strong>
   <%= @patient.date_admission %>
   <br>
   <strong>Date autopsy:</strong>
   <%= @patient.date_autopsy %>
   <br>
   <strong>Time:</strong>
   <%= @patient.time_of_autopsy %>
 </div>
 <div id="case" class="col-sm-2">
   <strong>Case:</strong>
   <%= @patient.case %>
   <br>
   <strong>Hospital:</strong>
   <%= @patient.hospital %>
 </div>

 <div id="doctors" class="col-sm-3"> 
   <strong>Pathologist:</strong>
   <%= @patient.pathologist%>
   <br>
   <strong>Physician:</strong>
   <%= @patient.physician %>
   <br>
   <strong>Attendant:</strong>
   <%= @patient.attendant %>
   <br>
   <strong>Prosector:</strong>
   <%= @patient.prosector %>
   <br>
 </div>
 </div>

 <hr>

 <div class="row">
	 <div class="col-sm-12">
  <strong>Restrictions:</strong>
  <%= @patient.restrictions.html_safe %>
 </div>
 </div>
 <br>
<%= link_to 'Edit Patient Information', edit_patient_path(@patient), class: 'btn btn-primary' %> 
<%# if ! @patient.organ_weight.nil? %>
<%#=  link_to 'Edit Organ Weight', edit_organ_weight_path(@patient), class: 'btn btn-success' %> 
<%# else %>
<%#=  link_to 'New Organ Weight', new_organ_weight_path(@patient), class: 'btn btn-success' %> 
<%# end %>
<%# if ! @patient.body_measurement.nil? %>
<%#=  link_to 'Edit Body Measurement', edit_body_measurement_path(@patient), class: 'btn btn-success' %> 
<%# else %>
<%#=  link_to 'New Body Measurement', new_body_measurement_path(@patient), class: 'btn btn-success' %> 
<%# end %>
<%#= link_to 'Back', patients_path, class: 'btn btn-primary' %>
 <hr>
 <%# if ! @patient.organ_weight.nil? %>
  <%#= render file: 'app/views/organ_weights/show.html.erb' %>
 <%# else %>
  <%#= link_to 'Add Organ Weight' ,new_organ_weight_path(@patient), class: 'btn btn-warning'%>
 <%# end%>
 
 <%# if ! @patient.body_measurement.nil? %>
  <%#= render file: 'app/views/body_measurements/show.html.erb' %>
 <%# else %>
  <%#= link_to 'Add Body Measurement' ,new_body_measurement_path(@patient), class: 'btn btn-warning'%>
 <%# end%>
 <hr>
  <%= link_to 'Back', patients_path, class: 'btn btn-success' %>
 <hr>